name: swipe_direction_detector
description: A flutter package detect left ,right,up, down siwpes.
version: 0.0.2
homepage: https://github.com/woodjobber/swipe_detector.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0